language: go
go:
- 1.13.x
before_install:
- go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
install:
- 
script:
- go get -t -v ./...
- env GOOS=linux GOARCH=amd64 go build -o gophercoin-linux-amd64
- goversioninfo -icon=./gophercoin.ico
- env GOOS=windows GOARCH=amd64 go build -o gophercoin-windows-amd64.exe

deploy:
  edge: true
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: gopherchain/gophercoin
    branches:    
      only:      
      - master 
  skip_cleanup: true
  file:
  - gophercoin-windows-amd64.exe
  - gophercoin-linux-amd64
  draft: true